# autonomous_app_creator.py — fully autonomous app creation
import os, json, time, random
from arena_core.agent_runtime import get_agents, save_agents
from arena_core.agent_utils import create_mutated_agent
from arena_core.lineage_tracker import record_lineage
from arena_core.pdf_reader_agent import ingest_all_pdfs

EXAMPLES_DIR = os.path.join(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")), "examples")

def generate_app(agent, base_name=None):
    """
    Create a fully autonomous app project based on agent knowledge and templates
    """
    base_name = base_name or f"{agent.name}_app"
    ts = int(time.time())
    app_name = f"{base_name}_{ts}"
    path = os.path.join(EXAMPLES_DIR, f"{app_name}.py")

    try:
        ingest_all_pdfs()  # feed knowledge first
        # build app logic using agent knowledge + pattern injection
        content = f"# {app_name} — auto-generated by {agent.name}\n"
        content += f"# Knowledge summary: {getattr(agent, 'knowledge_summary', 'None')}\n\n"
        content += "def main():\n"
        content += f"    print('Hello from autonomous app {app_name}!')\n"
        content += "    # TODO: Extend with self-evolved logic\n\n"
        content += "if __name__ == '__main__':\n"
        content += "    main()\n"

        with open(path, "w") as f:
            f.write(content)

        new_agent = create_mutated_agent(agent, type(agent))
        if new_agent:
            new_agent.path = path
            new_agent.mutation_desc = "autonomous_app_creation"
            record_lineage(new_agent.name, parent=agent.name, mutation_desc=new_agent.mutation_desc)
            print(f"[AutonomousApp] Created app: {app_name} from agent {agent.name}")
            return new_agent
    except Exception as e:
        print(f"[AutonomousApp] Failed to create app from {agent.name}: {e}")
        return None

def generate_apps_for_top_agents(top_n=3):
    agents = get_agents()
    created_agents = []
    top_agents = sorted(agents, key=lambda a: getattr(a, "score",0), reverse=True)[:top_n]
    for ag in top_agents:
        new = generate_app(ag)
        if new:
            created_agents.append(new)
    save_agents(agents + created_agents)
    return [a.name for a in created_agents]

if __name__ == "__main__":
    names = generate_apps_for_top_agents(3)
    print("[AutonomousApp] Apps generated:", names)
